### ISSUE TITLE
Allow setting dashicon on widget in customizer.

### ISSUE THREAD

**Issue by theenoahmason** [dreamsicle-io/wp-backstage#84]
Widget icons in the customizer are purely CSS based. They provide the unicode character for dashicons on `.widget-title::before`. Add a config key that will allow for adding an inline style to set this on the customizer panel.

**Below is the CSS that is used to set the widget icon in the available-widgets section of the customizer:**

```css
#available-widgets [class*=text] .widget-title:before {
    content: "\f478";
}
```
